* Kati

Kati is a web-based system to generate catalogs of new items in the
library. It takes [[https://www.loc.gov/marc/bibliographic/][MARC21 XML]] bibliographic data from the library
system and produces catalogs in various formats such as [[http://www.access-for-all.ch/en/pdf-lab/pdf-accessibility-checker-pac.html][accessible PDF]]
or [[https://en.wikipedia.org/wiki/DTBook][DTBook XML]]. The PDFs contain either all of the new catalog items or
various subsets of the items such as all new large print books or all
new audio books for example.

For the DTBook there are actually two variations produced. One can be
used for the production of Braille with a separate tool chain while
the other is imported into [[http://www.daisy.org/project/obi][Obi]] for audio production.

** Build and Installation
Build with [[https://github.com/technomancy/leiningen][Leiningen]] using the [[https://github.com/immutant/lein-immutant][lein immutant plugin]].

#+BEGIN_SRC shell
lein immutant war --nrepl-start --nrepl-port 40021
#+END_SRC

Since we depend on an unreleased version of [[https://xmlgraphics.apache.org/fop/][Apache FOP]] for the moment
we have to build with LEIN_SNAPSHOTS_IN_RELEASE enabled:

#+BEGIN_SRC shell
LEIN_SNAPSHOTS_IN_RELEASE=yes lein immutant war --nrepl-start --nrepl-port 40021
#+END_SRC

Deploy the resulting war file in [[http://wildfly.org/][Wildfly]].

** Documentation

- [[https://github.com/sbsdev/catalog/wiki][Wiki]]
- [[https://sbsdev.github.io/catalog][API Docs]]

Essentialy the system is a small service where dumps of the library
database can be uploaded and catalogs in various formats downloaded.
There is a web interface to download catalogs and, if this cannot be
automated, also to upload database exports from the library database.

A database contains all items. The catalogs are produced based on
those items.

** Configuration and Dependencies
Installation and configuration can be done using an [[https://github.com/sbsdev/sbs-infrastructure/blob/master/kati.yml][ansible
installation script]] which automates the whole process.

Mostly you will need [[http://wildfly.org/][Wildfly]], and some fonts.

** License

Copyright © 2015-2016 Swiss Library for the Blind, Visually Impaired and Print Disabled.

Distributed under the [[http://www.gnu.org/licenses/agpl-3.0.html][GNU Affero General Public License]]. See the file LICENSE.
